### ISSUE TITLE
Cant connect since last firmware of TRADFRI ?

### ISSUE THREAD

**Issue by ImChiip** [wschenk/tradfri-cli#7]
Hello

Since the last update of TRADFRI V1.13.19 it is impossible for me to connect the gateway

I have an error on the response from the gateway even though it is on the network

> C:\Users\arnau\Documents\Nodejs\Ikea-tradfri-test>node --trace-warnings  connection.js 
> Looking up IKEA Tradfri gateway on your network
> Connecting to TRADFRI-Gateway-c4ac59eb0443.local
> Getting identity from security code
> (node:8516) UnhandledPromiseRejectionWarning: Error: The gateway did not respond in time.
>     at TradfriClient.<anonymous> (C:\Users\arnau\Documents\Nodejs\Ikea-tradfri-test\node_modules\node-tradfri-client\build\tradfri-client.js:179:39)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\arnau\Documents\Nodejs\Ikea-tradfri-test\node_modules\node-tradfri-client\build\tradfri-client.js:4:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
>     at emitUnhandledRejectionWarning (internal/process/promises.js:168:15)
>     at processPromiseRejections (internal/process/promises.js:247:11)
>     at processTicksAndRejections (internal/process/task_queues.js:94:32)
> (node:8516) Error: The gateway did not respond in time.
>     at TradfriClient.<anonymous> (C:\Users\arnau\Documents\Nodejs\Ikea-tradfri-test\node_modules\node-tradfri-client\build\tradfri-client.js:179:39)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\arnau\Documents\Nodejs\Ikea-tradfri-test\node_modules\node-tradfri-client\build\tradfri-client.js:4:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> (node:8516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
>     at emitDeprecationWarning (internal/process/promises.js:180:11)
>     at processPromiseRejections (internal/process/promises.js:249:13)
>     at processTicksAndRejections (internal/process/task_queues.js:94:32)

You have same issue ? 

Kr

**Comment by silas229** [comment]
Same problem :/

**Comment by alejandromume** [comment]
After playing and testing the code, I managed to solve the problem by updating `node-tradfri-client`. Simply by running `npm i node-tradfri-client`.

**Comment by iratenewt** [comment]
same problem, alejandromume's fix didn't solve my problem. Is this still a problem for anyone else?
